#!/usr/bin/env bash
set -e

if [[ $(tput lines) > 35 ]]; then
  preview_height=30
elif [[ $(tput lines) > 25 ]]; then
  preview_height=20
else
  preview_height=0
fi

if [ "$args" == "mine" ]; then
  GH_FORCE_TTY='100%' gh pr list --assignee @me --limit 100 | \
    tail -n +4 | \
    fzf --ansi \
      --preview-window down:30 \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      -m \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh pr view {1} | bat -p --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh pr view --web {}
else
  GH_FORCE_TTY='100%' gh pr list --state all --limit 100 | \
    tail -n +4 | \
    fzf --ansi \
      --preview-window down:30 \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      -m \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh pr view {1} | bat -p --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh pr view --web {}
fi

